theme: jekyll-theme-hacker
title: mpv-music
description: "A blazing-fast terminal music player and mpv based music library browser with fuzzy search and zero daemons â€” mpv-music (also known as mpv music / mpvmusic)."
keywords: "mpv-music, mpv music, terminal music player, mpv wrapper, mpvmusic, library manager, music"
